package com.example.tokitoki.ui.constants

object TestTags {
    const val SIGN_IN_CONTENTS = "SIGN_IN_CONTENTS"
    const val REGISTER_WITH_EMAIL_CONTENTS = "REGISTER_WITH_EMAIL_CONTENTS"
    const val REGISTER_WITH_EMAIL_TEXT_FIELD = "REGISTER_WITH_EMAIL_TEXT_FIELD"
    const val REGISTER_WITH_EMAIL_ERROR_DIALOG = "REGISTER_WITH_EMAIL_ERROR_DIALOG"
}
